### ISSUE TITLE
Deprecate demo

### ISSUE THREAD

**Issue by tscpp** [kolint/kolint#110]
Demo shouldn't be used anymore because we have specification (/spec) and the CLI to test with.

- [x] Fix CLI output flag - https://github.com/kolint/kolint/issues/109
- [ ] Remove the demo folder - https://github.com/kolint/kolint/tree/f0a8528/demo
- [ ] Remove the demo script from package.json https://github.com/kolint/kolint/blob/f0a8528d361fe3bfd938efdc8da513f17b9f175e/package.json#L30
- [ ] Remove the .vscode launch demo configuration from `/.vscode/settings.json`
